=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/dtd/farmacia.dtd
<!ELEMENT farmacia (medicamentos)>
<!ELEMENT medicamentos (medicamento+)>
<!ELEMENT medicamento (nombre,precio,presentacion+,(caja | frasco))>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre fabricante NMTOKEN #REQUIRED>
<!-- 

    NMTOKEN: una única palabra
    CDATA: texto y/o números
    #REQUIRED obligatorio incluir el atributo
    #IMPLIED opcional incluir el atributo

-->
<!ELEMENT precio (#PCDATA)>
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT caja (#PCDATA)>
<!ELEMENT frasco (#PCDATA)>

=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/dtd/farmacia.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-model href = "farmacia.rng"?>
<!DOCTYPE farmacia SYSTEM "farmacia.dtd">
<farmacia>
    <medicamentos>
        <medicamento>
            <nombre fabricante = "pfizer">Viagra</nombre>
            <precio>64</precio>
            <presentacion>4</presentacion>
            <presentacion>8</presentacion>
            <presentacion>12</presentacion>
            <caja>Cartón</caja>
        </medicamento>
        <medicamento>
            <nombre fabricante = "Bayer">Aspirina</nombre>
            <precio>4</precio>
            <presentacion>12</presentacion>
            <caja>Cartón</caja>
        </medicamento>
        <medicamento>
            <nombre fabricante = "Moderna">Vacuna COVID19</nombre>
            <precio>64</precio>
            <presentacion>4</presentacion>
            <frasco>Cristal</frasco>
        </medicamento>
    </medicamentos>
</farmacia>
