=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/libreria-pt-2/libreria.dtd
<!ELEMENT libreria (castellano,otrosIdiomas)>
<!ELEMENT castellano (libro+)>
<!ELEMENT libro (autor,edicionEspecial,saga+,paquete*,(descuento|regalo))>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT edicionEspecial (#PCDATA)>
<!ELEMENT saga (#PCDATA)>
<!ELEMENT paquete (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
<!ELEMENT regalo (#PCDATA)>

<!ELEMENT otrosIdiomas (libroOI+)>
<!ELEMENT libroOI (autor,edicionEspecial,saga+,paquete*,(descuento|regalo),idioma)>
<!ELEMENT idioma (#PCDATA)>

=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/libreria-pt-2/libreria.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!-- DeclaraciÃ³n xml -->

<!DOCTYPE libreria SYSTEM "libreria.dtd">
<!-- Linkar dtd -->

<?xml-model href="libreria.rng"?>
<!-- Linkar rng -->

<!-- Estructura -->
<libreria>
    <castellano>
        <libro>
            <autor></autor>
            <edicionEspecial></edicionEspecial>
            <saga></saga>
            <paquete></paquete>
            <!-- Descuento CHOICE -->
            <descuento></descuento>
        </libro>
        <libro>
            <autor></autor>
            <edicionEspecial></edicionEspecial>
            <!-- SAGA ONE OR MORE -->
            <saga></saga>
            <saga></saga>
            <!-- PAQUETE ZERO OR MORE -->
            <paquete></paquete>
            <paquete></paquete>
            <!-- REGALO CHOICE -->
            <regalo></regalo>
        </libro>
        <libro>
            <autor></autor>
            <edicionEspecial></edicionEspecial>
            <saga></saga>
            <regalo></regalo>
        </libro>
    </castellano>

    <otrosIdiomas>
        <libroOI>
            <autor></autor>
            <edicionEspecial></edicionEspecial>
            <saga></saga>
            <paquete></paquete>
            <regalo></regalo>
            <idioma></idioma>
        </libroOI>
    </otrosIdiomas>

</libreria>
