=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/muebleria/muebleria.dtd
<!ELEMENT muebleria (interior, exterior)>
<!ELEMENT interior (muebles)>
<!ELEMENT muebles (mueble+)>
<!ELEMENT mueble (nombre, precio, descripcion, oferta?, familia?, combinado*, (montaje | transporte | garantiaExtra))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT oferta (#PCDATA)>
<!ATTLIST oferta temporada CDATA #IMPLIED>
<!ELEMENT familia (#PCDATA)>
<!ATTLIST familia actualizado NMTOKEN #FIXED "sÃ­">
<!ELEMENT combinado (#PCDATA)>
<!ELEMENT montaje (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT garantiaExtra (#PCDATA)>

<!ELEMENT exterior (muebles)>

=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/muebleria/muebleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE muebleria SYSTEM "muebleria.dtd"> -->
<?xml-model href="muebleria.rng"?>
<muebleria>
    <interior>
        <muebles>
            <mueble>
                <nombre></nombre>
                <precio></precio>
                <descripcion></descripcion>
                <oferta temporada="San Valentín"></oferta>
                <familia actualizado="sí"></familia>
                <combinado></combinado>
                <montaje></montaje>
            </mueble>
            <mueble>
                <nombre></nombre>
                <precio></precio>
                <descripcion></descripcion>
                <oferta></oferta>
                <familia></familia>
                <garantiaExtra></garantiaExtra>
            </mueble>
            <mueble>
                <nombre></nombre>
                <precio></precio>
                <descripcion></descripcion>
                <combinado></combinado>
                <combinado></combinado>
                <combinado></combinado>
                <transporte></transporte>
            </mueble>
        </muebles>
    </interior>

    <exterior>
        <muebles>
            <mueble>
                <nombre></nombre>
                <precio></precio>
                <descripcion></descripcion>
                <oferta></oferta>
                <combinado></combinado>
                <montaje></montaje>
            </mueble>
        </muebles>
    </exterior>
</muebleria>
