=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/pizzeria/pizzeria.dtd
<!ELEMENT pizzeria (pizzas,vinos)>
<!ELEMENT pizzas (pizza+)>
<!ELEMENT pizza (nombre,precio,masa,borde,foto,topping,tamaño?,extra*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda NMTOKEN #REQUIRED>
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa masaTipo NMTOKEN #REQUIRED>
<!ELEMENT borde (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT topping EMPTY>
<!ELEMENT tamaño (#PCDATA)>
<!ELEMENT extra (#PCDATA)>

<!ELEMENT vinos (vino+)>
<!ELEMENT vino (marca,tipo,precio)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

=== Deviitt11/LMSGI/2ª EVAL/TEMA 4/pizzeria/pizzeria.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="./pizzeria.xslt" type="text/xsl"?>

<?xml-model href="pizzeria.rng"?>

<!DOCTYPE pizzeria SYSTEM "pizzeria.dtd">

<pizzeria>
    <pizzas>
        <pizza>
            <nombre>Margarita</nombre>
            <precio moneda="euros">12</precio>
            <masa masaTipo="integral">Fina</masa>
            <borde>Fina</borde>
            <foto>https://www.hogarmania.com/archivos/202303/pizza-margarita-portada-1280x720x80xX.jpg</foto>
            <topping></topping>
            <tamaño>Familiar</tamaño>
            <extra>Queso</extra>
            <extra>Orégano</extra>
        </pizza>
        <pizza>
            <nombre>4 Quesos</nombre>
            <precio moneda="euros">12</precio>
            <masa masaTipo="integral">Fina</masa>
            <borde>Relleno</borde>
            <foto>https://www.cocinatis.com/archivos/202207/CTIS0093-receta-pizza-cuatro-quesos_B3N6zYV_large_16x9.jpg</foto>
            <topping></topping>
        </pizza>
        <pizza>
            <nombre>Pollo</nombre>
            <precio moneda="euros">12</precio>
            <masa masaTipo="integral">Fina</masa>
            <borde>Normal</borde>
            <foto>https://www.gastronomiaycia.com/wp-content/photos/pizza_pollopibarbacoa2.jpg</foto>
            <topping></topping>
        </pizza>
    </pizzas>

    <vinos>
        <vino>
            <marca>Uno</marca>
            <tipo>Tinto</tipo>
            <precio moneda="euros">12</precio>
        </vino>
        <vino>
            <marca>Dos</marca>
            <tipo>Blanco</tipo>
            <precio moneda="euros">15</precio>
        </vino>
    </vinos>
</pizzeria>
